import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="text-[#393f46]">
      <Head>
        <title>Coworking Ceuma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='snap-mandatory overflow-scroll snap-y w-screen h-screen'>

        {/* Home */}
        <div className="snap-center w-full h-full">
          <div className='h-1/2 bg-[#f5f5f5] w-full'>
            <article className="prose prose-slate lg:prose-lg w-full m-0 max-w-none">
              <div className='flex'>
                <div className='flex flex-col px-20 pt-10'>
                  <h1>Um espaço para criatividade</h1>
                </div>
                <div className='flex flex-col mr-10'>
                  <h3 className='flex justify-center items-center'>
                    Sozinhos podemos fazer tão pouco, juntos podemos fazer tanto... <br />
                  </h3>
                  <p className='flex justify-end pt-2 pr-10'>
                      Helen Keller
                    </p>
                  <Image src="/coworking-main.jpg" className='rounded-2xl w-full  h-3/4' width={1000} height={1000} alt="coworking"></Image>
                </div>
              </div>

            </article>
          </div>
          <div className='h-1/2 bg-[#1d1d1d]'>

          </div>


        </div>

        {/* Branding */}
        <div className="snap-center w-full h-full">
        
          <div className='h-1/2 article prose lg:prose-sm max-w-none bg-[#f5f5f5] flex justify-center items-center w-full'>
          <h1 className='self-start px-10 pt-5'>Parceiros</h1>
            <div className="w-full flex text-center self-center items-center justify-center -ml-60 ">
             
                <Image src="/branding/adobe.svg" className='px-10' width={220} height={220} alt="coworking"></Image>
                <Image src="/branding/ebay.svg" className='px-10' width={220} height={220} alt="coworking"></Image>
                <Image src="/branding/loom.svg" className='px-10' width={220} height={220} alt="coworking"></Image>
                <Image src="/branding/tailwindcss_logo.svg" className='px-10' width={220} height={220} alt="coworking"></Image>
              
            
            </div>
          </div>

          <div className='h-1/2 text-white article prose lg:prose-sm max-w-none bg-[#1d1d1d] w-full '>

          <h1 className='flex self-start items-end justify-end px-10 pt-5 text-white w-full'>Quem está a frente do Coworking?</h1>
            <div className="w-full flex text-center self-center items-center justify-center  ">
             
               <Image src="/Prof_Edilson.png" className='mx-5 mb-5 shadow-xl rounded-2xl' width={500} height={200} alt="coworking"></Image>
               
            
            </div>

          </div>
        </div>


        <div className="snap-center w-full h-full">
          <div className='h-1/2 bg-[#f5f5f5] w-full'>
            <article className="prose prose-slate lg:prose-lg w-full m-0 max-w-none">
              <div className='flex'>
                <div className='flex flex-col px-10 mx-40 py-10'>
                  <h1 className='w-full'>Projeto 1</h1>
                </div>
                <div className='flex flex-col'>
                  <p className='flex justify-center items-center'>
                    Sozinhos podemos fazer tão pouco, juntos podemos fazer tanto... <br />
                    

                  </p>
                  <Image src="/coworking-main.jpg" className='pt-20' width={1220} height={1220} alt="coworking"></Image>
                </div>
              </div>

            </article>
          </div>
          <div className='h-1/2 bg-[#1d1d1d]'>

          </div>
        </div>


        <div className="snap-center w-full h-full">
          <div className='h-1/2 bg-[#f5f5f5] w-full'>
            <article className="prose prose-slate lg:prose-lg w-full m-0 max-w-none">
              <div className='flex'>
                <div className='flex flex-col px-20 py-10'>
                  <h1>Um espaço para criatividade</h1>
                </div>
                <div className='flex flex-col'>
                  <p className='flex justify-center items-center'>
                    Sozinhos podemos fazer tão pouco, juntos podemos fazer tanto... <br />
                    


                  </p>
                  <Image src="/coworking-main.jpg" className='pt-20' width={1220} height={1220} alt="coworking"></Image>
                </div>
              </div>

            </article>
          </div>
          <div className='h-1/2 bg-[#1d1d1d]'>

          </div>
        </div>

      </div>

     
    </div>
  )
}
