import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import Projeto, { demosType, projetoType } from '../components/projeto'
import { SlideshowLightbox, initLightboxJS } from 'lightbox.js-react'
import { useEffect } from 'react';

type responseType = {
  nome: string,
  descricao: string,
  thumbnail: string,
  demos: Array<demosType>
}

type parceiroType = {
  nome: string,
  descricao: string,
  thumbnail: string
}


export async function getServerSideProps() {

  const projetos = (await axios.get("https://coworking-backend-thexarcano.vercel.app/api/projetos")).data
  const parceiros = (await axios.get("https://coworking-backend-thexarcano.vercel.app/api/parceiros")).data


  return {
    props: {
      projetos,
      parceiros
    }
  }
}


export default function Home(props: { projetos: Array<responseType>, parceiros: any }) {


  useEffect(() => {
    initLightboxJS("2C59-354E-7777-CE47", "individual");
  });


  return (
    <div className="text-[#393f46]">
      <Head>
        <title>Coworking Ceuma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='snap-mandatory overflow-scroll snap-y w-screen h-screen'>

        {/* Seção 1 */}
        <div className="snap-center w-full h-full">
          {/* Home */}
          <div className='h-1/2 bg-[#f5f5f5] w-full'>
            <article className="prose prose-slate lg:prose-lg w-full m-0 max-w-none">
              <div className='flex'>
                <div className='flex flex-col px-20 pt-10'>
                  <h1>Um espaço para criatividade</h1>
                </div>
                <div className='flex flex-col mr-10'>
                  <h3 className='flex justify-center items-center'>
                    Sozinhos podemos fazer tão pouco, juntos podemos fazer tanto... <br />
                  </h3>
                  <p className='flex justify-end pt-2 pr-10'>
                    Helen Keller
                  </p>
                  <Image src="/coworking-main.jpg" className='rounded-2xl w-full  h-3/4' width={1000} height={1000} alt="coworking"></Image>
                </div>
              </div>

            </article>
          </div>
          {/* Extras */}
          <div className='h-1/2 bg-[#1d1d1d]'>

          </div>


        </div>

        {/* Seção 2 */}
        <div className="snap-center w-full h-full">


          {/* Branding */}
          <div className='h-[50vh] article prose lg:prose-sm max-w-none bg-[#1d1d1d] w-full'>
            <div className='h-full'>
              <h1 className='flex h-1/6 self-start justify-center px-10 pt-5 text-white'>Nossos Parceiros</h1>
              <div className="w-full h-4/6 flex text-center self-center items-center justify-center">


                <SlideshowLightbox lightboxIdentifier="lightbox1" theme="lightbox" framework="next" images={props.parceiros}>
                  {props.parceiros.map((parceiro: parceiroType, key: number) => (
                    <Image
                      src={parceiro.thumbnail}
                      alt={parceiro.descricao}
                      className='w-2/4 h-2/4 '
                      key={key}
                      height={500}
                      width={500}
                      data-lightboxjs="lightbox1"
                      quality={80}
                    />
                  ))}
                </SlideshowLightbox>


              </div>
            </div>
          </div>

          {/* Quem está a frente? */}

          <div className='h-[50vh] article prose lg:prose-sm max-w-none bg-[#A2A2A3] w-full '>

            <h1 className='flex self-start items-end justify-center px-10 pt-5  w-full'>Quem está a frente do Coworking?</h1>
            <div className="w-full flex text-center justify-between self-center items-center px-64  ">

              <Image src="/edilson.webp" className='mx-5 mb-5 shadow-xl rounded-2xl' width={400} height={200} alt="coworking"></Image>
              <div>
                <h1>Edilson Carlos Silva Lima</h1>
                <h5>
                  Especialista em ANALISE E DESENVOLVIMENTO DE SISTEMA pela Universidade Federal do Maranhão , Brasil(2009).<br />
                </h5>
              </div>

            </div>

          </div>
        </div>


        {/* Projetos */}

        <div className="w-full h-full">

          {props.projetos.map((projeto, key) =>
            <Projeto key={key} Parentkey={key} {...projeto} showMainTitle={key == 0 ? true : false} />
          )}

        </div>



      </div >

    </div>
  )
}

